### ISSUE TITLE
Responses

### ISSUE THREAD

**Issue by horrificsquid** [horrificsquid/MostlyMoviesBot#1]
Want the bot to respond with a letterboxd film link if the following message is sent by user:

'!f [film title]'

**Comment by pandeyganesha** [comment]
from config import SETTINGS

I am unable to understand the use of this module. It is throwing error on my machine. (btw I am also new to it.)

**Comment by horrificsquid** [comment]
> 

I'm not sure either. I believe the SETTINGS is added to the library root config _init_.py
I'm not sure if the location will be the same for everyone but for me it's: Mostly_Movies/venv/Lib/site-packages/config/_init_.py

The code I added is:
`def SETTINGS():
         return None`

But I'm not sure what settings need adding. 
Same goes for:
`def conn_url():
        return None`

This is maybe the Letterboxd url? Maybe I'm way off.

**Comment by horrificsquid** [comment]
Added a folder called "Other Root Files (Possibly Useful)". this has the init.py I think the settings belongs in (at bottom of code at the moment)

**Comment by pandeyganesha** [comment]
I think you are making project using Django or flask or something like that. And I don't know how to use them. I can just code in python.
I don't even have these files and folder in my forked repo.
venv/Lib/site-packages/config/init.py

I actually wanted to code for the main topic. Regarding the bot response. So, may be you can help me out to help you out.

**Comment by horrificsquid** [comment]
I am using Pycharm to code (https://www.jetbrains.com/pycharm/). Not sure if this is how the structure is put together.
The bot itself is working for me with the basic text responses working, and are easily editable.
The main.py, bot.py and responses.py are all you need for that element. Make sure to add your bot "TOKEN" here (in bot.py):

```
def run_discord_bot():
    TOKEN = ''
    intents = discord.Intents.default()
    intents.message_content = True
    client = discord.Client(intents=intents)
```

**Comment by Ganesh910** [comment]
![image](https://user-images.githubusercontent.com/39578603/227771781-81639ad5-4297-4e07-96a1-ca74611d95eb.png)

I have installed pycharm too, but still getting the same error.

**Comment by pandeyganesha** [comment]
![image](https://user-images.githubusercontent.com/39578603/227772176-38222081-1797-40c9-ad41-f07ae66cff2d.png)

I have installed pycharm too. Installed config with pip install config too. Still this error is showing up. I searched google too, still can't resolve this error.

And this error comes when I run main.py

**Comment by horrificsquid** [comment]
Delete line 5 in responses.py then the basic function of the bot will work. The api.py is for all the Letterboxd movie link responses I'm trying to get working.

**Comment by pandeyganesha** [comment]
I commented out line 5 in responses and it is causing more errors because the program is using that inside program.

You bot.py is calling responses, response is calling api.py, And api.py is calling settings.
removing any of the line is causing problem.

I tried to find settings function in __init__() file in other projects too. And none of the projects online have such SETTINGS function. So, I don't know what is that doing in your code. There is no such function like SETTINGS online in that file.

I tried all ways. I even created settings function myself, but That did not help much because It is meant to be returning some kind of array or dictionary.

Please try running this code on some other system yourself by cloning it from git and see it yourself.

**Comment by horrificsquid** [comment]
> I commented out line 5 in responses and it is causing more errors because the program is using that inside program.
> 
> You bot.py is calling responses, response is calling api.py, And api.py is calling settings. removing any of the line is causing problem.
> 
> I tried to find settings function in **init**() file in other projects too. And none of the projects online have such SETTINGS function. So, I don't know what is that doing in your code. There is no such function like SETTINGS online in that file.
> 
> I tried all ways. I even created settings function myself, but That did not help much because It is meant to be returning some kind of array or dictionary.
> 
> Please try running this code on some other system yourself by cloning it from git and see it yourself.

I have added a directory called "Stripped Down Working bot" this 100% works with the simple call and response.

**Comment by pandeyganesha** [comment]
Synced my fork with new files and things working fine now.
Now let me clarify,

If anyone types "!f <movie name>", the bot must send the messsage "https://letterboxd.com/film/" + "movie-name/".

that's all what you want? means is there some way you want the url to be generated or just concatenating url prefix with the name in above format you mentioned. Because sometimes url may not work if user have written wrong spelling of movie, or it may return wrong movie url in case of two movies with same name.

**Comment by horrificsquid** [comment]
I will add the function of optional date that should solve the issue of multiple movies. I won't have a chance to have a proper look until the weekend, but I think I understand a lot more of what code needs adding; so will test it over the weekend.

**Comment by pandeyganesha** [comment]
Sure, I have added the required feature. And let me know if I can help further.
